#Config manager
ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

  auth:
    jwtSecret: C*F-JaNdRgUkXp2r5u8x/A?D(G+KbPeShVmYq3t6v9y$B&E)H@McQfTjWnZr4u7x
    jwtExpirationMs: 14400000

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost